# Generated by Django 2.0.4 on 2018-04-15 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Embed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('started', 'started'), ('finished', 'finished'), ('failed', 'failed')], default='pending', max_length=20)),
                ('method_option', models.CharField(choices=[('embed_1', 'DWT Based and Arnold Transform to Image')], default='0', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_input', models.TextField(default='')),
                ('audio_input', models.TextField(default='')),
                ('key', models.TextField(default='')),
                ('accessToken', models.TextField(default='')),
                ('audio_output', models.TextField(null=True)),
                ('result', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Extract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('started', 'started'), ('finished', 'finished'), ('failed', 'failed')], default='pending', max_length=20)),
                ('method_option', models.CharField(choices=[('extract_1', 'DWT Based and Arnold Transform to Image')], default='0', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('watermarked_audio_input', models.TextField(default='')),
                ('original_audio_input', models.TextField(default='')),
                ('size', models.TextField(default='')),
                ('key', models.TextField(default='')),
                ('accessToken', models.TextField(default='')),
                ('image_output', models.TextField(null=True)),
                ('result', models.TextField(null=True)),
            ],
        ),
    ]
