# Generated by Django 2.0.4 on 2018-04-15 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='embed',
            name='user_id',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='extract',
            name='user_id',
            field=models.TextField(null=True),
        ),
    ]
