# Generated by Django 2.0.4 on 2018-04-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='argument',
        ),
        migrations.AddField(
            model_name='job',
            name='accessToken',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='audio_input',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='audio_output',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='image_input',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='image_output',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='key',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='result',
            field=models.TextField(null=True),
        ),
    ]
