# Generated by Django 2.0.4 on 2018-04-13 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_services', '0002_auto_20180408_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='Embed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('started', 'started'), ('finished', 'finished'), ('failed', 'failed')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_input', models.TextField(null=True)),
                ('audio_input', models.TextField(null=True)),
                ('key', models.TextField(null=True)),
                ('accessToken', models.TextField(null=True)),
                ('audio_output', models.TextField(null=True)),
                ('result', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Extract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('started', 'started'), ('finished', 'finished'), ('failed', 'failed')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_input', models.TextField(null=True)),
                ('audio_input', models.TextField(null=True)),
                ('key', models.TextField(null=True)),
                ('accessToken', models.TextField(null=True)),
                ('image_output', models.TextField(null=True)),
                ('audio_output', models.TextField(null=True)),
                ('result', models.TextField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
